### ISSUE TITLE
missing definition when compiling with vfd

### ISSUE THREAD

**Issue by cdechamplain** [att-cloud/dpdk#1]
The dpdk seems to be missing a definition:

/nobackup/cdechamp/vfd-master/src/vfd/sriov.c: In function ?vf_msb_event_callback?:
/nobackup/cdechamp/vfd-master/src/vfd/sriov.c:896:9: error: variable ?p? has initializer but incomplete type
  struct rte_eth_mb_event_param p = _(struct rte_eth_mb_event_param_) param;
         ^
compilation terminated due to -Wfatal-errors.

**Comment by ScottDaniels** [comment]
Code checked into master was not dpdk 2.2 based but dpdk 1404 based.  Correct sriov.c was restored and the current commit for master is correct.
